Update asset migration
planetmint/planetmint-driver-python pull request #66
Opened 2022-10-27 15:11 UTC by LaurentMontBlanc

## Description
- updated to planetmint-transactions@0.2.0
- adjusted for assets change in transaciton spec v3.0

2022-10-27 15:17 UTC, LaurentMontBlanc commented
@eckelj the unit tests need to be re-run after the planetmint update-asset-migration branch is merged because it uses the main branch. I reverted this before merging this branch into main again

2022-11-09 07:57 UTC, eckelj requested changes

2022-11-09 07:57 UTC, eckelj commented on Makefile
> +	@$(DC) run --rm planetmint-driver flake8 --max-line-length 119 planetmint_driver tests
don't we use black?

2022-11-09 07:57 UTC, eckelj commented on docs/usage.rst
> +=======
previous merge wasn't done properly

2022-11-09 07:57 UTC, eckelj commented on docs/usage.rst
> +<<<<<<< HEAD
previous merge wasn't done properly

2022-11-09 07:57 UTC, eckelj commented on planetmint_driver/common/transaction.py
> +# Copyright Planetmint GmbH and Planetmint contributors
didn't we plan to use planetmint/transactions instead of having that file local? or does this file complement the transactions package?

2022-11-09 08:36 UTC, LaurentMontBlanc commented on planetmint_driver/common/transaction.py
> +# Copyright Planetmint GmbH and Planetmint contributors
no, this does not complement anything. was an oversight on my end. removed the module now

2022-11-09 08:38 UTC, eckelj approved these changes

2022-11-09 08:39 UTC, merged